<?php

namespace AppBundle\Repository;

/**
 * annonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class annonceRepository extends \Doctrine\ORM\EntityRepository
{
}
