<?php

namespace AppBundle\Repository;

/**
 * chatUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class chatUserRepository extends \Doctrine\ORM\EntityRepository
{
}
