<?php

namespace AppBundle\Repository;

/**
 * chatMessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class chatMessageRepository extends \Doctrine\ORM\EntityRepository
{
}
