<?php

namespace AppBundle\Repository;

/**
 * congesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class congesRepository extends \Doctrine\ORM\EntityRepository
{
}
