<?php

namespace AppBundle\Repository;

/**
 * formationUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class formationUserRepository extends \Doctrine\ORM\EntityRepository
{
}
