<?php

namespace AppBundle\Repository;

/**
 * salarieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class salarieRepository extends \Doctrine\ORM\EntityRepository
{
}
