<?php

namespace AppBundle\Repository;

/**
 * sujetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class sujetRepository extends \Doctrine\ORM\EntityRepository
{
}
