<?php

namespace AppBundle\Repository;

/**
 * themeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class themeRepository extends \Doctrine\ORM\EntityRepository
{
}
